export type AppLanguage = 'en' | 'hi';

export const LANGUAGE_OPTIONS: Array<{ code: AppLanguage; name: string; native: string }> = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
];

export const translations: Record<AppLanguage, Record<string, string>> = {
  en: {
    home: 'Home',
    scan: 'Scan',
    pricing: 'Pricing',
    login: 'Login',
    register: 'Register',
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Login to access your dashboard',
    createAccount: 'Create Account',
    createAccountSubtitle: 'Join KrishiScan to detect crop health faster.',
    fullName: 'Full Name',
    email: 'Email Address',
    password: 'Password',
    continueGuest: 'Continue as Guest',
    secureData: 'Your data is secure and encrypted',
    or: 'or',
    pleaseFill: 'Please fill in all fields',
    fullNameRequired: 'Please enter your full name',
    selectLanguage: 'Select Language',
    dashboardTitle: 'Scan Your Crop',
    dashboardSubtitle: 'Upload a clear photo of the affected leaf for instant AI-powered diagnosis',
    cropType: 'Select Crop Type',
    sugarcane: 'Sugarcane',
    otherCrops: 'Other Crops',
    language: 'Language',
    english: 'English',
    hindi: 'हिन्दी',
    tips: 'Tips for Best Results',
    tip1: 'Take photo in good natural lighting',
    tip2: 'Focus clearly on the affected area',
    tip3: 'Avoid blurry or dark images',
    tip4: 'Scan one leaf at a time',
    uploadText: 'Click or drag to upload',
    uploadMeta: 'PNG, JPG, JPEG up to 10MB',
    noFile: 'No file selected',
    chooseFile: 'Choose File',
    scanNow: 'Scan Now',
    locationRequired: 'Location permission is required for crowdsourced crop reporting.',
    selectImage: 'Please select an image first',
    diseasePrediction: 'Disease Prediction',
    confidence: 'Confidence',
    diagnosisSummary: 'Diagnosis Summary',
    recommendedActions: 'Recommended Actions',
    backDashboard: 'Back to Dashboard',
    logout: 'Logout',
    user: 'User',
    authUser: 'Authenticated',
    guestBox: 'User',
  },
  hi: {
    home: 'होम',
    scan: 'स्कैन',
    pricing: 'कीमत',
    login: 'लॉग इन',
    register: 'रजिस्टर',
    welcomeBack: 'वापसी पर स्वागत है',
    loginSubtitle: 'अपने डैशबोर्ड तक पहुंचने के लिए लॉग इन करें',
    createAccount: 'अकाउंट बनाएं',
    createAccountSubtitle: 'KrishiScan में शामिल हों और फसल की सेहत जल्दी पहचानें।',
    fullName: 'पूरा नाम',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    continueGuest: 'गेस्ट के रूप में जारी रखें',
    secureData: 'आपका डेटा सुरक्षित और एन्क्रिप्टेड है',
    or: 'या',
    pleaseFill: 'कृपया सभी फील्ड भरें',
    fullNameRequired: 'कृपया पूरा नाम दर्ज करें',
    selectLanguage: 'भाषा चुनें',
    dashboardTitle: 'अपनी फसल स्कैन करें',
    dashboardSubtitle: 'प्रभावित पत्ते की स्पष्ट फोटो अपलोड करें और तुरंत एआई आधारित निदान प्राप्त करें',
    cropType: 'फसल प्रकार चुनें',
    sugarcane: 'गन्ना',
    otherCrops: 'अन्य फसलें',
    language: 'भाषा',
    english: 'English',
    hindi: 'हिन्दी',
    tips: 'सर्वोत्तम परिणाम के लिए सुझाव',
    tip1: 'अच्छे प्राकृतिक प्रकाश में फोटो लें',
    tip2: 'प्रभावित क्षेत्र को स्पष्ट रूप से केंद्रित करें',
    tip3: 'धुंधली या अंधेरी तस्वीरों से बचें',
    tip4: 'एक बार में एक पत्ता स्कैन करें',
    uploadText: 'अपलोड करने के लिए क्लिक करें',
    uploadMeta: 'PNG, JPG, JPEG अधिकतम 10MB',
    noFile: 'कोई फाइल चयनित नहीं',
    chooseFile: 'फाइल चुनें',
    scanNow: 'अभी स्कैन करें',
    locationRequired: 'सामूहिक फसल रिपोर्टिंग के लिए लोकेशन अनुमति आवश्यक है।',
    selectImage: 'कृपया पहले एक फोटो चुनें',
    diseasePrediction: 'रोग पूर्वानुमान',
    confidence: 'विश्वास',
    diagnosisSummary: 'निदान सारांश',
    recommendedActions: 'सुझावित कार्रवाई',
    backDashboard: 'डैशबोर्ड पर वापस',
    logout: 'लॉग आउट',
    user: 'उपयोगकर्ता',
    authUser: 'प्रमाणित',
    guestBox: 'उपयोगकर्ता',
  },
};

export const getText = (language: AppLanguage, key: string): string => {
  return translations[language]?.[key] ?? translations.en[key] ?? key;
};
